@startuml

title Usecase for Information system

left to right direction

actor Actor1
actor :Complex Actor2:

Actor1 <|-- :Complex Actor2:

rectangle Software {
    usecase (Usecase1)
    usecase (Usecase2)
    
    Actor1 --> (Usecase1)
    Actor1 --> (Usecase2)
}

@enduml

