' https://real-world-plantuml.com/umls/5650639363244032
@startuml

left to right direction

actor :Simple customer:
actor clerk

rectangle checkout {
	:Simple customer: -- (checkout)
	(checkout) .> (payment) : include
	(help) .> (checkout) : extends
	(checkout) -- clerk
}

@enduml
