@startuml

title Example of Activity Diagram 

start

:The program analyzes user data; 
note right: Using RegExp validator11111111

if (Is Data Correct111111111111?) then (yes)
  :Thank you!;
else (no)
  :Your data is incorrect!;
endif

stop

@enduml
