name: JSON Linter
on:
 # оброка лише події типу push
 # для декількох значень використовується дужки, наприклад, [push, pull_request]
 push:
  # обробка подій лише для окремої гілки
  branches: LW11
jobs:
 json_linter_test:
  # використання Docker-image із вказаною версією ОС
  runs-on: ubuntu-latest
  steps:
  - name: checkout
    # клонування репозиторія для подальшої роботи з файлами на сервері 
    # в каталозі $GITHUB_WORKSPACE
    uses: "actions/checkout@v3"
  - name: Start JSON Linter
    # виконнання декількох послідовних команд shell-інтерпретатором
    run: |
     npm i -g @prantlf/jsonlint
     jsonlint $GITHUB_WORKSPACE/file.json
    
