# https://github.com/marketplace/actions/super-linter
name: Program Code Linter
on:
  push:
    branches-ignore: [master, main]
jobs:
  ProgramCodeLinter:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         reporter: 'github-pr-check'
         tool_name: 'testtool'
